---
grails:
    profile: web
    codegen:
        defaultPackage: org.mountsinai.mortalitytriggersystem
    spring:
        transactionManagement:
            proxies: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
        buildDate: '@info.app.buildDate@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

server:
    contextPath: '/@info.app.name@'
    port: '9090'

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
            excel: application/vnd.ms-excel
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
endpoints:
    jmx:
        unique-names: true

---
hibernate:
    cache:
        queries: true
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

environments:
    development:
        dataSources:
            SECURE:
                dbCreate: none
                dialect: "org.hibernate.dialect.Oracle10gDialect"
                driverClassName: "oracle.jdbc.OracleDriver"
                #jndiName: "SecurePool"

                # # # # #
                url: "jdbc:oracle:thin:@10.2.10.83:1521:edrtest"
                username: "Appl"
                password: "applsecsystem"

            dataSource:
                logSql: "true"
                dbCreate: none
                dialect: "org.hibernate.dialect.Oracle10gDialect"
                driverClassName: "oracle.jdbc.OracleDriver"
                url: "jdbc:oracle:thin:@10.2.10.84:1521:MSINTRD"
                username: "MTT_DEV"
                password: "Mit3v1"
    test:
        dataSources:
            SECURE:
                dbCreate: none
                dialect: "org.hibernate.dialect.Oracle10gDialect"
                driverClassName: "oracle.jdbc.OracleDriver"
                #jndiName: "SecurePool"

                # # # # #
                url: "jdbc:oracle:thin:@10.2.10.83:1521:edrtest"
                username: "Appl"
                password: "applsecsystem"

            dataSource:
                dbCreate: none
                dialect: "org.hibernate.dialect.Oracle10gDialect"
                driverClassName: "oracle.jdbc.OracleDriver"
                url: "jdbc:oracle:thin:@10.2.10.84:1521:MSINTRD"
                username: "MTT_DEV"
                password: "Mit3v1"
    production:
        dataSources:
            SECURE:
                dbCreate: none
                dialect: "org.hibernate.dialect.Oracle10gDialect"
                driverClassName: "oracle.jdbc.OracleDriver"
                jndiName: "SecurePool"

                # # # # #
                #url: "jdbc:oracle:thin:@10.2.10.83:1521:edrtest"
                #username: "Appl"
                #password: "applsecsystem"
                # # # # #

            dataSource:
                dbCreate: none
                dialect: "org.hibernate.dialect.Oracle10gDialect"
                driverClassName: "oracle.jdbc.OracleDriver"
                jndiName: "MTTPool"

                # # # # #
                #url: "jdbc:oracle:thin:@10.2.10.84:1521:MSINTRD"
                #username: "MTT_DEV"
                #password: "Mit3v1"
                # # # # #